### ISSUE TITLE
panic when closing a stream due to error response in OnStreamReqeust

### ISSUE THREAD

**Issue by vivekskrishna** [envoyproxy/go-control-plane#1023]
his occurs when a envoy instance tries to establish a stream to control palne but it repeatedly rejects it. this occurs once in approx 10 stream request to try and register the envoy to the control plane.
(*Callbacks).OnStreamOpen","level":"debug","msg":"NEW STREAM ID 12 is open of type ","time":"2024-10-08T23:44:02-07:00"}
(*Callbacks).OnStreamRequest","level":"debug","msg":"new request","time":"2024-10-08T23:44:02-07:00"}
(*Callbacks).OnStreamClosed","level":"debug","msg":"stream 12 of node instance1 closed\n","time":"2024-10-08T23:44:02-07:00"}
(*Callbacks).OnStreamClosed","level":"debug","msg":"STREAM ID 12 is closed for node instance1","time":"2024-10-08T23:44:02-07:00"}
(*Callbacks).OnStreamClosed","level":"error","msg":" Error in instance reg to control plane","time":"2024-10-08T23:44:02-07:00"}
panic: send on closed channel

goroutine 115 [running]:
github.com/envoyproxy/go-control-plane/pkg/server/sotw/v3.(*server).process.func1()
        /go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.13.0/pkg/server/sotw/v3/xds.go:100 +0x1b
created by github.com/envoyproxy/go-control-plane/pkg/server/sotw/v3.(*server).process in goroutine 113
        /go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.13.0/pkg/server/sotw/v3/xds.go:99 +0xaff

**Comment by vivekskrishna** [comment]
looks like this was reported in https://github.com/envoyproxy/go-control-plane/issues/789
