### ISSUE TITLE
Panic occurred when serializing OkResponse for ext_authz

### ISSUE THREAD

**Issue by fenngwd** [envoyproxy/go-control-plane#142]
## Problem

Hi all

Panic occurred when my external authorization service marshal OkResponse. 

Below are stack trace(out-of-order, the first line should be deepest trace):

```
github.com/envoyproxy/go-control-plane/envoy/api/v2/core.(*HeaderValueOption).MarshalTo(0xc0004c6d50, 0xc000e462ae, 0x4, 0x4, 0x16, 0x6ab, 0x0)
created by google.golang.org/grpc.(*Server).serveStreams.func1
    /build/vendor/google.golang.org/grpc/server.go:802 +0x86
    /build/vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2alpha/external_auth.pb.go:592 +0x15d

github.com/envoyproxy/go-control-plane/envoy/service/auth/v2alpha.(*CheckResponse).MarshalTo(0xf2e460, 0xc000e45c00, 0x6b2, 0x6b2, 0x6b2, 0x6b2, 0xa3ca40)
github.com/envoyproxy/go-control-plane/envoy/service/auth/v2alpha.(*CheckResponse_OkResponse).MarshalTo(0xf2b4b8, 0xc000e45c00, 0x6b2, 0x6b2, 0xc000795950, 0x440057, 0x700)
google.golang.org/grpc/encoding/proto.codec.Marshal(0xa3ca40, 0xf2e460, 0x1, 0xc000795a68, 0xc000795b88, 0x92e3d2, 0xc000795bc0)
    /build/vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2alpha/external_auth.pb.go:624 +0xdf
github.com/envoyproxy/go-control-plane/envoy/service/auth/v2alpha.(*OkHttpResponse).MarshalTo(0xf402e0, 0xc000e45c03, 0x6af, 0x6af, 0x6c1, 0x3, 0xc000152e00)
github.com/envoyproxy/go-control-plane/envoy/api/v2/core.(*HeaderValue).MarshalTo(0xc00049e900, 0xc000e462b0, 0x2, 0x2, 0x12, 0x2, 0x0)
    /build/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/core/base.pb.go:1878 +0x27d
    /build/vendor/google.golang.org/grpc/server.go:1139 +0xd58
    /build/vendor/google.golang.org/grpc/server.go:681 +0xa1
google.golang.org/grpc.(*Server).sendResponse(0xc000001680, 0xafabc0, 0xc000097380, 0xc0004b2400, 0xa3ca40, 0xf2e460, 0x0, 0x0, 0xc000898827, 0x0, ...)
goroutine 2175 [running]:
    /build/vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2alpha/external_auth.pb.go:553 +0x16d
    /build/vendor/github.com/envoyproxy/go-control-plane/envoy/api/v2/core/base.pb.go:1908 +0xe5
    /build/vendor/google.golang.org/grpc/server.go:683 +0x9f
panic: runtime error: index out of range
google.golang.org/grpc.(*Server).handleStream(0xc000001680, 0xafabc0, 0xc000097380, 0xc0004b2400, 0x0)
google.golang.org/grpc.encode(0x7f87ea759030, 0xf5dd70, 0xa3ca40, 0xf2e460, 0xf5dd70, 0x9ac4a0, 0xaefd40, 0x0, 0x0)
github.com/envoyproxy/go-control-plane/envoy/service/auth/v2alpha.(*CheckResponse).Marshal(0xf2e460, 0xa3ca40, 0xf2e460, 0x7f87ea7590e8, 0xf2e460, 0x1)
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000898600, 0xc000001680, 0xafabc0, 0xc000097380, 0xc0004b2400)
    /build/vendor/google.golang.org/grpc/encoding/proto/proto.go:70 +0x19c
    /build/vendor/google.golang.org/grpc/server.go:957 +0x514
    /build/vendor/google.golang.org/grpc/rpc_util.go:511 +0x5e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001680, 0xafabc0, 0xc000097380, 0xc0004b2400, 0xc000150ae0, 0xf2ca90, 0x0, 0x0, 0x0)
    /build/vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2alpha/external_auth.pb.go:569 +0x7f
```

## Vendor Info
I'm using go module for my dependency management.

```
require (
	github.com/dgrijalva/jwt-go v3.2.0+incompatible
	github.com/envoyproxy/go-control-plane v0.6.3
	github.com/fsnotify/fsnotify v1.4.7
	github.com/gogo/googleapis v1.1.0
	github.com/gogo/protobuf v1.1.1
	github.com/lyft/protoc-gen-validate v0.0.11 // indirect
	golang.org/x/net v0.0.0-20181114220301-adae6a3d119a // indirect
	google.golang.org/grpc v1.16.0
)
```

## Golang version
1.11

## Releated Links
https://github.com/gogo/protobuf/issues/523
https://github.com/gogo/protobuf/issues/485

**Comment by kyessenov** [comment]
Is this because of nil in some slice? Could something be done here to avoid having nils in slices?
